# __Introduction to Tensors__

Tensors are fundamental data structures in deep learning and are similar to multi-dimensional arrays. They are a generalization of vectors and matrices to higher dimensions and provide a way to represent and manipulate numerical data efficiently.

Tensors can be seen as containers for numerical data that can be organized into a specific shape or size.

Let's understand how it works.


## Steps to be followed:
1. Import the required libraries
2. Create the rank zero Tensor
3. Create the rank one Tensor
4. Create the rank two Tensor
5. Create the rank three Tensor
6. Convert a Tensor to a NumPy array
7. Perform basic mathematics with Tensors
8. Initialize the Tensor
9. Broadcast the x and y variables

### Step 1: Import the required libraries

- Import two libraries, TensorFlow and NumPy.
- TensorFlow is a popular open-source machine learning framework that provides a set of tools and functionalities for building and training machine learning models.
- NumPy is a Python library for numerical computations that provide support for handling multi-dimensional arrays and mathematical operations on them.

In [1]:
!pip install tensorflow==2.17.0 scikeras==0.13.0 keras==3.2.0

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.3 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [3]:
# Disable oneDNN optimizations to avoid potential minor numerical differences caused by floating-point round-off errors.
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

In [4]:
# Import TensorFlow and NumPy libraries
import tensorflow as tf
import numpy as np

### Step 2: Create the rank zero Tensor
- The rank is also known as order, degree, or ndims.
- The **tf.constant(4)** creates a constant Tensor with a single value of **4**.
- The **tf.constant()** function is used to create Tensors with fixed values that cannot be changed.
- The **rank_0_tensor** variable holds the created Tensor.
- The **print(rank_0_tensor)** prints the value of the Tensor, which,  in this case, is __4__.

In [2]:
# Create a rank 0 tensor (scalar) with a constant value of 4
rank_0_tensor = tf.constant(4)
# Print the rank 0 tensor
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


**Observation:**

- As seen above, the output represents a TensorFlow Tensor object with a value of 4, an empty shape, and an **int32** data type.

### Step 3: Create the rank one Tensor
- Define a rank one Tensor in TensorFlow with the values **[2.0, 4.0, 5.0]** and print the Tensor object.

In [3]:
# Create a rank 1 tensor (vector) with values [2.0, 4.0, 5.0]
rank_1_tensor = tf.constant([2.0, 4.0, 5.0])
# Print the rank 1 tensor
print(rank_1_tensor)

tf.Tensor([2. 4. 5.], shape=(3,), dtype=float32)


**Observations:**

- As seen above, the output represents a one-dimensional Tensor with three elements: **2.0**, **4.0**, and **5.0**.
- The shape of the Tensor is **(3, ),** indicating that it has a size of 3 along the first dimension.
- The dtype of the Tensor is **float32**, indicating that the elements are of type float.

### Step 4: Create the rank two Tensor
- Create a rank two Tensor, which is a two-dimensional array, using the **tf.constant** function.
- The Tensor has a shape of (3, 2), meaning it has three rows and two columns, and the elements of the Tensor are specified as [1, 2], [3, 4], and [5, 6].

In [4]:
# Create a rank 2 tensor (matrix) with shape (3, 2) and specified values
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
# Print the rank 2 tensor
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


**Observations:**

- The output represents a rank two Tensor with a shape of (3, 2) and a dtype of float16. The Tensor contains the following elements arranged in a 3x2 matrix, as seen above.
- Each element of the Tensor is a floating-point number with a precision of 16 bits.

### Step 5: Create the rank three Tensor

- Define a rank three Tensor with a shape of (3, 2, 5), indicating three layers, each containing two rows and five columns.
- The Tensor represents a 3D array of integers, where each element corresponds to a specific position within the layers, rows, and columns.
- The values increase sequentially from __0__ to __29__, arranged in a structured pattern within the Tensor.



In [5]:
# Create a rank 3 tensor with shape (3, 2, 5) and sequential values from 0 to 29
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
# Print the rank 3 tensor
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


**Observations:**
- The output represents a rank three Tensor with a shape of (3, 2, 5) and a data type of int32.
- It contains three layers, each consisting of two rows and five columns, with integer values ranging from 0 to 29 arranged in a structured pattern within the Tensor.

### Step 6: Convert a Tensor to a NumPy array

- Convert the rank two array present here to a NumPy array.
- The Tensors often contain float datatype.

In [6]:
# Convert the rank 2 tensor to a NumPy array
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

**Observations:**
- The output represents a two-dimensional array (matrix) with a shape of (3, 2) and a data type of float16.
- It contains floating-point values ranging from 1.0 to 6.0, organized in three rows and two columns.

### Step 7: Perform basic mathematics on Tensors
- Declare two variables **a** and **b**.
- The **tf.add(a, b)** operation performs element-wise addition between Tensors a and b.
- The **tf.multiply(a, b)** operation performs element-wise multiplication between Tensors a and b.
- The **tf.matmul(a, b)** operation performs matrix multiplication between Tensors a and b.


In [7]:
# Declare two 2x2 tensors a and b
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])

# Perform element-wise addition
print(tf.add(a, b), "\n")
# Perform element-wise multiplication
print(tf.multiply(a, b), "\n")
# Perform matrix multiplication
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



**Observations:**
- Tensors perform element-wise addition and multiplication.
- The given output consists of three TensorFlow Tensors, each representing a 2x2 matrix with integer values.

  ### Step 8: Initialize the Tensor

  - The **tf.reduce_max(c)** calculates the maximum value in Tensor c.
  - The **tf.math.argmax(c)** returns the index of the maximum value in Tensor c.
  - The **tf.nn.softmax(c)** applies the softmax activation function to Tensor c, which computes the probability distribution over the elements of c.


In [9]:
# Initialize a tensor c with specified values
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
# Calculate the maximum value in tensor c
print(tf.reduce_max(c))
# Find the index of the maximum value in tensor c
print(tf.math.argmax(c))
# Apply the softmax function to tensor c
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


**Observation:**
- It calculates the maximum value in Tensor c, finds the indices of the maximum values, and applies the softmax function to obtain a probability distribution Tensor.

### Step 9: Broadcast the X and Y variables
- Broadcast the two variables **x** and **y**.
- Smaller Tensors are stretched automatically to fit larger Tensors.
- All of these are the same computation.
- Perform element-wise multiplication between Tensors x and a scalar value of 2, between Tensors x and scalar y, and between Tensors x and Tensors z.

In [10]:
# Declare a 1x3 tensor x
x = tf.constant([1, 2, 3])

# Declare scalar and 1x3 tensor for broadcasting
y = tf.constant(2)
z = tf.constant([2, 2, 2])

# Perform element-wise multiplication with scalar
print(tf.multiply(x, 2))
# Perform element-wise multiplication with another scalar
print(x * y)
# Perform element-wise multiplication with another tensor
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


**Observations:**

- We can see that even though the shape of y is not the same as that of x, we can still multiply these two variables.
- So, this is an example of broadcasting, where smaller Tensors are stretched automatically to fit larger Tensors.

#### Reshaping Tensors

In [11]:
# Create a tensor x with shape (3, 1)
x = tf.constant([[1], [2], [3]])
# Print the shape of the tensor x
print(x.shape)

(3, 1)


**Observation:**
- The `shape` function returns a tensor-shaped object that shows the size along each axis.

In [12]:
reshaped = tf.reshape(x , [1,3])

In [13]:
# Print the shapes of the original and reshaped tensors
print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


**Observation:**
- The Tensor has been reshaped to the desired dimensions, providing the intended configuration.

#### Different Types of Tensors
- **Ragged Tensor**: Tensor with the variable number of
elements along some axes is called Ragged Tensor.

In [14]:
# Create a ragged tensor with a variable number of elements along some axes
ragged_list = [
    [0,1,2,3],
    [4,5],
    [6,7,8],
    [9]]

ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


- **Scalar String Tensor**: It is a datatype, which means that data can be represented as strings (variable-length byte arrays) in Tensors.

In [15]:
# Create a scalar string tensor
scalar_string_tensor = tf.constant("gray wolf")
# Print the scalar string tensor
print(scalar_string_tensor)

tf.Tensor(b'gray wolf', shape=(), dtype=string)


**Observation**
- We can represent
the strings as Tensors.
