In [1]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

In [2]:
type(list1)

list

In [3]:
list1 + list2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
import numpy as np

In [5]:
trans_list1 = np.array(list1)

In [6]:
type(trans_list1)

numpy.ndarray

In [7]:
trans_list2 = np.array(list2)

In [8]:
type(trans_list2)

numpy.ndarray

In [9]:
trans_list1 + trans_list2

array([ 7,  9, 11, 13, 15])

In [10]:
trans_list2

array([ 6,  7,  8,  9, 10])

In [11]:
trans_list2[2]

8

In [12]:
trans_list2[-3]

8

In [13]:
var1 = [[10,20,30],[40,50,60],[70,80,90]]

In [14]:
type(var1)

list

In [15]:
new_var1 = np.array(var1)

In [16]:
new_var1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [17]:
new_var1[2,1]

80

In [18]:
new_var1[2][1]

80

In [19]:
new_var1[1]

array([40, 50, 60])

In [20]:
new_var1[:,1]

array([20, 50, 80])

In [21]:
new_var1[1:3,1:3]

array([[50, 60],
       [80, 90]])

In [22]:
np.mean(new_var1)

50.0

In [23]:
np.var(new_var1)

666.6666666666666

In [24]:
np.std(new_var1)

25.81988897471611

In [25]:
np.log(new_var1)

array([[2.30258509, 2.99573227, 3.40119738],
       [3.68887945, 3.91202301, 4.09434456],
       [4.24849524, 4.38202663, 4.49980967]])

In [27]:
result = np.sqrt(new_var1)

In [29]:
np.sqrt(new_var1)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669],
       [8.36660027, 8.94427191, 9.48683298]])

In [28]:
np.round(result,decimals=2)

array([[3.16, 4.47, 5.48],
       [6.32, 7.07, 7.75],
       [8.37, 8.94, 9.49]])

In [30]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [33]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [39]:
np.random.rand(5) #Generate values that will follow uniform distribution

array([0.06101809, 0.66644931, 0.34249948, 0.75252036, 0.39530368])

In [44]:
np.random.randn(3) #Generate values that will follow normal distribution

array([ 0.91166535,  0.56262025, -0.57226889])

In [62]:
np.random.randint(5,100,3)

array([69, 25, 21])

In [64]:
sample = np.random.randint(5,100,20)

In [65]:
sample.shape

(20,)

In [69]:
sample_result = sample.reshape(2,10)

In [70]:
sample_result.shape

(2, 10)

In [73]:
import numpy as np
print(np.__version__)

1.24.3


In [74]:
sample_result

array([[90, 12, 70, 28, 37, 20, 31, 96, 53, 68],
       [25, 97, 30, 13, 32, 11, 68, 77, 47, 35]])

In [75]:
np.max(sample_result)

97

In [76]:
np.min(sample_result)

11

In [77]:
np.argmax(sample_result)

11

In [78]:
np.argmin(sample_result)

15

In [79]:
sample

array([90, 12, 70, 28, 37, 20, 31, 96, 53, 68, 25, 97, 30, 13, 32, 11, 68,
       77, 47, 35])

In [80]:
sample[4]

37

In [81]:
sample[4:10]

array([37, 20, 31, 96, 53, 68])

In [83]:
sample[[0,2,4]]

array([90, 70, 37])

In [85]:
sample[0:4] = 100

In [86]:
sample

array([100, 100, 100, 100,  37,  20,  31,  96,  53,  68,  25,  97,  30,
        13,  32,  11,  68,  77,  47,  35])

In [95]:
sample_array = np.arange(10,21)

In [96]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [97]:
subset_sample_array = sample_array[0:6]

In [98]:
subset_sample_array

array([10, 11, 12, 13, 14, 15])

In [99]:
subset_sample_array[:] = 100

In [100]:
subset_sample_array

array([100, 100, 100, 100, 100, 100])

In [101]:
sample_array

array([100, 100, 100, 100, 100, 100,  16,  17,  18,  19,  20])

In [102]:
sample_array = np.arange(10,21)

In [103]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [104]:
copy_array = sample_array.copy()

In [105]:
copy_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [106]:
subset_sample_array = copy_array[0:5]

In [107]:
subset_sample_array

array([10, 11, 12, 13, 14])

In [108]:
subset_sample_array[:] = 100

In [109]:
copy_array

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19,  20])

In [110]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [111]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [112]:
np.save('sample_result',sample_array)

In [113]:
sample_array_from_file = np.load('sample_result.npy')

In [114]:
sample_array_from_file

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [115]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [116]:
sample_result

array([[100, 100, 100, 100,  37,  20,  31,  96,  53,  68],
       [ 25,  97,  30,  13,  32,  11,  68,  77,  47,  35]])

In [117]:
np.savez('2_arrays.npz',a=sample_array,b=sample_result)

In [118]:
archived_arrays = np.load('2_arrays.npz')

In [119]:
archived_arrays['a']

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [120]:
archived_arrays['b']

array([[100, 100, 100, 100,  37,  20,  31,  96,  53,  68],
       [ 25,  97,  30,  13,  32,  11,  68,  77,  47,  35]])

In [122]:
archived_arrays['a']

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])