# __Slicing__

## __Agenda__
In this lesson, we will cover the following concepts with the help of examples:

- NumPy Array Slicing
  * Slicing 1D NumPy Arrays
  * Slicing Using Step Value
  * Slicing: 2D Array
  * Slicing: 3D Array
  * Negative Slicing

## __1. NumPy Array Slicing__

- In Python, slicing refers to moving elements from one index to another.
- Instead of using an index, the slice is passed as **[start:end]**.
- Another way to pass the slice is to add a step as **[start:end:step]**.
- In slicing, if the starting is not passed, it is considered as 0. If the step is not passed as 1 and if the end is not passed, it is considered as the length of the array in that dimension.

### __1.1 Slicing 1D NumPy Arrays__

#### Example 1: Use slicing to retrieve employee ratings for a team of seven employees in the first quarter from an array

In [1]:
import numpy as np
Employee_rating = np.array([1, 4, 3, 5, 6, 8, 9, 10, 12])
print(Employee_rating[1:7:2])

[4 5 8]


#### Example 2: Print the list of three subjects towards the end

In [2]:
Books = np.array(['Physics','DataScience','Maths','Python','Hadoop', 'OPPs', 'Java', 'Cloud'])
print(Books[5:])

['OPPs' 'Java' 'Cloud']


### __1.2 Slicing Using Step Value__

In [3]:
X = np.array([8, 7, 6, 5, 4, 3, 2, 1])
print(X[0:7:3])

[8 5 2]


### __1.3 Slicing: 2D Array__

In [4]:
Z = np.array([[11, 22, 33, 44, 55], [66, 77, 88, 99, 110]])
print(Z)

[[ 11  22  33  44  55]
 [ 66  77  88  99 110]]


In [5]:
print(Z[1, 2:5])

[ 88  99 110]


### __1.4 Slicing: 3D Array__

In [7]:
array_3d = np.array([[[1,2,3],[4,5,6],[20,21,22]],[[7,8,9],[10,11,12],[23,24,25]]])
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]
  [20 21 22]]

 [[ 7  8  9]
  [10 11 12]
  [23 24 25]]]


In [8]:
print(array_3d[0,1,1])

5


In [9]:
print(array_3d[0,1:,1:])

[[ 5  6]
 [21 22]]


In [ ]:
new_arr_2d = array_3d[0]
print(new_arr_2d)

[[ 1  2  3]
 [ 4  5  6]
 [20 21 22]]


In [ ]:
print(new_arr_2d[1:,1:])

[[ 5  6]
 [21 22]]


### __1.5 Negative Slicing__
- Negative slicing is the same as negative indexing, which is interpreted as counting from the end of an array.

![link text](https://labcontent.simplicdn.net/data-content/content-assets/Data_and_AI/ADSP_Images/Lesson_03_NumPy/5_Slicing/Image_1.png)

In [ ]:
# Negative slicing for 1D array
Neg_slice = np.array([13, 34, 58, 69, 44, 56, 37,24])
print(Neg_slice)

[13 34 58 69 44 56 37 24]


In [ ]:
print(Neg_slice[:-1])

[13 34 58 69 44 56 37]


In [ ]:
print(Neg_slice[0:7])

[13 34 58 69 44 56 37]


## __Assisted Practice__

### __Problem Statement:__

- Creating arrays for slicing:
  * Create a 1D NumPy array with at least 15 elements
  * Create a 2D NumPy array with a minimum of 4 rows and 5 columns
  * Create a 3D NumPy array with at least 2 matrices, each containing 3 rows and 4 columns

- Slicing 1D arrays:
  * Perform and demonstrate different slices on the 1D array, explore it using step values

- Slicing 2D arrays:
  * Slice rows and columns separately and in combination

- Slicing 3D arrays:
  * Perform slicing to access different matrices, rows within matrices, and elements within rows

- Negative slicing:
  * Implement negative slicing on 1D, 2D, and 3D arrays
  * Compare the outcomes of negative slicing with positive slicing