<a href="https://colab.research.google.com/github/priyankjangwan/PythonApps/blob/main/3_03_NumPy_Arithmetic_Statistical_and_String_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# __NumPy Arithmetic Statistical and String Functions__

## __Agenda__

In this lesson, we will cover the following concepts with the help of examples:
- Arithmetic Operations Using NumPy
  * Addition
  * Subtraction
  * Multiplication
  * Division
  * Power of
- Statistical Function in Numpy
  * Calculating Median, Mean, Standard Deviation, and Variance in the Array
  * Calculating Percentiles
- String Function in Numpy

## __1. Arithmetic Operations Using NumPy__ ##
### __1.1 Addition__ ###

In [ ]:
# Perform element-wise addition of two arrays using the 'np.add' method
import numpy as np
a = np.array([10,20,10])
b = np.array([10,20,20])
result = np.add(a,b)
print(result)

[20 40 30]


In [ ]:
#Broadcasting
c = np.array([10,20,10])
d = np.array([10])
result_new = np.add(c,d)
print(result_new)

[20 30 20]


### __1.2 Subtraction__ ###

In [ ]:
# Perform element-wise subtraction of two arrays using 'np.subtract' method
a = np.array([[30,40,60], [50,70,90]])
b = np.array([[10,20,30], [40,30,80]])
result = np.subtract(a,b)
print(result)

[[20 20 30]
 [10 40 10]]


### __1.3 Multiplication__ ###

In [ ]:
# Perform element-wise multiplication of two arrays using the 'np.multiply' method
a = np.array([30,20,10])
b = np.array([10,20,30])
result = np.multiply(a,b)
print(result)

[300 400 300]


### __1.4 Division__ ###

In [ ]:
# Perform element-wise division of two arrays using the 'np.divide' method
a = np.array([[1,2,1],[2,2,3]])
b = np.array([3,4,5])
result = np.divide(a,b)
print(result)

[[0.33333333 0.5        0.2       ]
 [0.66666667 0.5        0.6       ]]


### __1.5 Power of__ ###

In [ ]:
# Perform element-wise power operation where each element in 'a' is raised to the corresponding element in 'b' using the 'np.power' method
a = np.array([2,2,2,2,2])
b = np.array([2,3,4,5,6])
c = np.power(a,b)
print(c)

[ 4  8 16 32 64]


In [ ]:
e = np.array(1)
f = np.array([3,6,12,24,48,64])
g = np.add(e,f)
print(e+f)

[ 4  7 13 25 49 65]


## __2. Statistical Function in Numpy__ ##
### __2.1 Calculating Median, Mean, Standard Deviation, and Variance in the Array__ ###

In [ ]:
# Median
array = np.array([[4,3,2],[10,1,0],[5,8,24]])
np.median(array)
print(np.median(array))
# Mean
np.mean(array)
print(np.mean(array))
# Standard Deviation
np.std(array)
print(np.std(array))
# Variance
np.var(array)
print(np.var(array))

4.0
6.333333333333333
6.944222218666553
48.22222222222222


### __2.2 Calculating Percentiles__ ###
- The `np.percentile()` function is used to compute the nth percentile of the array elements.
- The nth percentile value should be in between 0 and 100.

In [ ]:
# Find the value under the 50th percentile of the NumPy array.
print(np.percentile(array,50))
print(np.percentile(array,25))
print(np.percentile(array,75))
print(np.percentile(array,20))
print(np.percentile(array,40))
print(np.percentile(array,60))
print(np.percentile(array,80))

4.0
2.0
8.0


## __3. String Function in Numpy__ ##

In [ ]:
# Perform element-wise string concatenation for two arrays of string
x = np.array(['Hello','World'])
y = np.array(['Welcome', 'Learners'])
result = np.char.add(x,y)
print(result)

['HelloWelcome' 'WorldLearners']


In [ ]:
# Replacing the old substring with the new substring
str = "Hello How Are You"
print(str)
z = np.char.replace(str, 'Hello', 'Hi')
print(z)

Hello How Are You
Hi How Are You


In [ ]:
# Converting all lowercase characters in a string to uppercase and vice-versa
str1 = "hello how are you"
print(str1)
z = np.char.upper(str1)
print(z)
str2 = "GREETINGS OF THE DAY"
print(str2)
s = np.char.lower(str2)
print(s)

hello how are you
HELLO HOW ARE YOU
GREETINGS OF THE DAY
greetings of the day


## __Assisted Practice__

### __Problem Statement:__

Consider the following arrays:

- Arrays for Arithmetic Operations:
  * Array A: [15, 25, 35, 45, 55]
  * Array B: [5, 10, 15, 20, 25]

- Array for Statistical Operations:
  * Array C: [12, 22, 32, 42, 52, 62, 72, 82, 92, 102]

- Arrays for String Functions:
  * String Array X: ['Hello', 'Data', 'Science', 'Class', 'Learners']
  * String Array Y: ['World', 'Analysis', 'is', 'Fun', '2023']
  
  
__Steps to Perform:__

1. Perform element-wise addition, subtraction, multiplication, division, and power operations on Arrays A and B
2. Calculate the median, mean, standard deviation, and variance for Array C
3. Concatenate corresponding elements of String Arrays X and Y
4. Convert all elements in String Array X to uppercase
5. Replace a specific substring in String Array Y with another substring