In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("Telco-Customer-Churn.csv")

In [7]:
R_STATE = 12345 # Set Random State
np.random.seed(R_STATE)

In [8]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [9]:
df.shape

(7043, 21)

In [10]:
df.drop(['customerID'], axis=1, inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   object 
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   object 
 3   Dependents        7043 non-null   object 
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   object 
 6   MultipleLines     7043 non-null   object 
 7   InternetService   7043 non-null   object 
 8   OnlineSecurity    7043 non-null   object 
 9   OnlineBackup      7043 non-null   object 
 10  DeviceProtection  7043 non-null   object 
 11  TechSupport       7043 non-null   object 
 12  StreamingTV       7043 non-null   object 
 13  StreamingMovies   7043 non-null   object 
 14  Contract          7043 non-null   object 
 15  PaperlessBilling  7043 non-null   object 
 16  PaymentMethod     7043 non-null   object 


In [12]:
df[df['TotalCharges'] == ' ']

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
488   Female              0     Yes        Yes       0           No   
753     Male              0      No        Yes       0          Yes   
936   Female              0     Yes        Yes       0          Yes   
1082    Male              0     Yes        Yes       0          Yes   
1340  Female              0     Yes        Yes       0           No   
3331    Male              0     Yes        Yes       0          Yes   
3826    Male              0     Yes        Yes       0          Yes   
4380  Female              0     Yes        Yes       0          Yes   
5218    Male              0     Yes        Yes       0          Yes   
6670  Female              0     Yes        Yes       0          Yes   
6754    Male              0      No        Yes       0          Yes   

         MultipleLines InternetService       OnlineSecurity  \
488   No phone service             DSL                  Yes   
753                 No              No  No internet service   
936                 No             DSL                  Yes   
1082               Yes              No  No internet service   
1340  No phone service             DSL                  Yes   
3331                No              No  No internet service   
3826               Yes              No  No internet service   
4380                No              No  No internet service   
5218                No              No  No internet service   
6670               Yes             DSL                   No   
6754               Yes             DSL                  Yes   

             OnlineBackup     DeviceProtection          TechSupport  \
488                    No                  Yes                  Yes   
753   No internet service  No internet service  No internet service   
936                   Yes                  Yes                   No   
1082  No internet service  No internet service  No internet service   
1340                  Yes                  Yes                  Yes   
3331  No internet service  No internet service  No internet service   
3826  No internet service  No internet service  No internet service   
4380  No internet service  No internet service  No internet service   
5218  No internet service  No internet service  No internet service   
6670                  Yes                  Yes                  Yes   
6754                  Yes                   No                  Yes   

              StreamingTV      StreamingMovies  Contract PaperlessBilling  \
488                   Yes                   No  Two year              Yes   
753   No internet service  No internet service  Two year               No   
936                   Yes                  Yes  Two year               No   
1082  No internet service  No internet service  Two year               No   
1340                  Yes                   No  Two year               No   
3331  No internet service  No internet service  Two year               No   
3826  No internet service  No internet service  Two year               No   
4380  No internet service  No internet service  Two year               No   
5218  No internet service  No internet service  One year              Yes   
6670                  Yes                   No  Two year               No   
6754                   No                   No  Two year              Yes   

                  PaymentMethod  MonthlyCharges TotalCharges Churn  
488   Bank transfer (automatic)           52.55                 No  
753                Mailed check           20.25                 No  
936                Mailed check           80.85                 No  
1082               Mailed check           25.75                 No  
1340    Credit card (automatic)           56.05                 No  
3331               Mailed check           19.85                 No  
3826               Mailed check           25.35                 No  
4380               Mailed check           20.00                 No

In [13]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [14]:
df['TotalCharges'] = df.apply(lambda x: float(x['TotalCharges']) if x['TotalCharges'] != ' ' else x['MonthlyCharges'], axis=1)

In [15]:
df.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  \
0              Yes           Electronic check           29.85         29.85   
1               No               Mailed check           56.95       1889.50   
2              Yes               Mailed check           53.85        108.15   
3               No  Bank transfer (automatic)           42.30       1840.75   
4              Yes           Electronic check           70.70        151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [16]:
dummy_columns = ['Partner','Contract','PaymentMethod','InternetService', 'gender','Dependents', 'PhoneService','MultipleLines', 'OnlineSecurity','OnlineBackup', 'DeviceProtection','TechSupport','StreamingTV','StreamingMovies', 'PaperlessBilling']

# Code here: One Hot Encoding of the categorical variables
df = pd.get_dummies(df, columns=dummy_columns, drop_first=True)

In [17]:
df.head()

SeniorCitizen  tenure  MonthlyCharges  TotalCharges Churn  Partner_Yes  \
0              0       1           29.85         29.85    No            1   
1              0      34           56.95       1889.50    No            0   
2              0       2           53.85        108.15   Yes            0   
3              0      45           42.30       1840.75    No            0   
4              0       2           70.70        151.65   Yes            0   

   Contract_One year  Contract_Two year  \
0                  0                  0   
1                  1                  0   
2                  0                  0   
3                  1                  0   
4                  0                  0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  ...  \
0                                      0                               1  ...   
1                                      0                               0  ...   
2                                      0                               0  ...   
3                                      0                               0  ...   
4                                      0                               1  ...   

   OnlineBackup_Yes  DeviceProtection_No internet service  \
0                 1                                     0   
1                 0                                     0   
2                 1                                     0   
3                 0                                     0   
4                 0                                     0   

   DeviceProtection_Yes  TechSupport_No internet service  TechSupport_Yes  \
0                     0                                0                0   
1                     1                                0                0   
2                     0                                0                0   
3                     1                                0                1   
4                     0                                0                0   

   StreamingTV_No internet service  StreamingTV_Yes  \
0                                0                0   
1                                0                0   
2                                0                0   
3                                0                0   
4                                0                0   

   StreamingMovies_No internet service  StreamingMovies_Yes  \
0                                    0                    0   
1                                    0                    0   
2                                    0                    0   
3                                    0                    0   
4                                    0                    0   

   PaperlessBilling_Yes  
0                     1  
1                     0  
2                     1  
3                     0  
4                     1  

[5 rows x 31 columns]

In [18]:
# Code here : Prepare X and y
X = df.drop(['Churn'], axis=1)

y = df['Churn'].map({'No': 0, 'Yes': 1})

In [19]:
# Code here: train test split 80:20, stratified sampling
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,

                                                    y,

                                                    train_size = 0.8,

                                                    stratify = y,

                                                    random_state = R_STATE)

In [20]:
# Code here: scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_sc = scaler.fit_transform(X_train)

X_test_sc = scaler.transform(X_test)

In [21]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LogisticRegressionCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [22]:
def get_metrics(y_true, y_pred, train=True):
    if train:
        l_message = "=========================== Training Set Metrics =========================="
    else:
        l_message = "=========================== Test Set Metrics =========================="
    print(l_message)
    print("Confusion Matrix")
    print(confusion_matrix(y_true=y_true, y_pred = y_pred))
    print()
    print(f"Accuracy Score {np.round(accuracy_score(y_true=y_true, y_pred = y_pred)*100,2)}%")
    print(f"Precision Score {np.round(precision_score(y_true=y_true, y_pred = y_pred)*100,2)}%")
    print(f"Recall Score {np.round(recall_score(y_true=y_true, y_pred = y_pred)*100,2)}%")
    print()

In [23]:
# Code here: Create a list of tuples for individual models that need to be considered - LogisticRegression, DecisionTree and SVM
models = [

    ('logreg', LogisticRegressionCV(random_state=R_STATE, cv=5)),

    ('dtree', DecisionTreeClassifier(max_depth=4,random_state=R_STATE)),

    ('svm', SVC(random_state=R_STATE, probability=True))

]

In [24]:
# Code here: Import VotingClassifier from Ensemle and instantiate a model (vc_model). Specify voting as hard
from sklearn.ensemble  import VotingClassifier
vc_model = VotingClassifier(estimators=models,voting='hard')
 

In [25]:
# Code here: Fit the ensemble on the scaled training set and evaluate on the scaled test set
vc_model.fit(X_train_sc,y_train)


VotingClassifier(estimators=[('logreg',
                              LogisticRegressionCV(cv=5, random_state=12345)),
                             ('dtree',
                              DecisionTreeClassifier(max_depth=4,
                                                     random_state=12345)),
                             ('svm',
                              SVC(probability=True, random_state=12345))])

In [26]:
y_tr_pred = vc_model.predict(X_train_sc)
y_ts_pred = vc_model.predict(X_test_sc)

In [27]:
get_metrics(y_true=y_train, y_pred = vc_model.predict(X_train_sc))

=========================== Training Set Metrics ==========================
Confusion Matrix
[[3807  332]
 [ 719  776]]

Accuracy Score 81.35%
Precision Score 70.04%
Recall Score 51.91%



In [28]:
get_metrics(y_true=y_test, y_pred = vc_model.predict(X_test_sc), train=False)

=========================== Test Set Metrics ==========================
Confusion Matrix
[[939  96]
 [182 192]]

Accuracy Score 80.27%
Precision Score 66.67%
Recall Score 51.34%



In [29]:
# Code here: Use the same tuple of models to instantiate VotingClassifier. This time, set voting as soft
soft_vc_model  = VotingClassifier(estimators=models,voting='soft')


In [30]:
# Code here: Fit the model
soft_vc_model.fit(X_train_sc,y_train)

VotingClassifier(estimators=[('logreg',
                              LogisticRegressionCV(cv=5, random_state=12345)),
                             ('dtree',
                              DecisionTreeClassifier(max_depth=4,
                                                     random_state=12345)),
                             ('svm',
                              SVC(probability=True, random_state=12345))],
                 voting='soft')

In [31]:
y_tr_pred = soft_vc_model.predict(X_train_sc)
y_ts_pred = soft_vc_model.predict(X_test_sc)

In [32]:
get_metrics(y_true = y_train, y_pred = y_tr_pred)

=========================== Training Set Metrics ==========================
Confusion Matrix
[[3839  300]
 [ 743  752]]

Accuracy Score 81.49%
Precision Score 71.48%
Recall Score 50.3%



In [33]:
get_metrics(y_true = y_test, y_pred = y_ts_pred, train=False)

=========================== Test Set Metrics ==========================
Confusion Matrix
[[942  93]
 [189 185]]

Accuracy Score 79.99%
Precision Score 66.55%
Recall Score 49.47%



# **Bagging Classifier**

In [34]:
# Code here: Import BaggingClassifier
from sklearn.ensemble import BaggingClassifier

In [40]:
# Code here: Create a model - bag_model. estimator is Decision Tree with max_depth=4, n_estimators = 100, oob_score=True
bag_model = BaggingClassifier(estimator=DecisionTreeClassifier(max_depth=4,random_state=R_STATE),
                              n_estimators=101,
                              random_state=R_STATE,
                              oob_score=True)
                              

In [41]:
# Code here: Fit the model
bag_model.fit(X_train_sc,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(max_depth=4,
                                                   random_state=12345),
                  n_estimators=101, oob_score=True, random_state=12345)

In [42]:
y_tr_pred = bag_model.predict(X_train_sc)
y_ts_pred = bag_model.predict(X_test_sc)

In [43]:
get_metrics(y_true = y_train, y_pred = y_tr_pred)

=========================== Training Set Metrics ==========================
Confusion Matrix
[[3832  307]
 [ 812  683]]

Accuracy Score 80.14%
Precision Score 68.99%
Recall Score 45.69%



In [44]:
get_metrics(y_true = y_test, y_pred = y_ts_pred, train=False)

=========================== Test Set Metrics ==========================
Confusion Matrix
[[944  91]
 [207 167]]

Accuracy Score 78.85%
Precision Score 64.73%
Recall Score 44.65%



In [46]:
print(f"OOB Score {bag_model.oob_score_}")

OOB Score 0.793574724884629


# **Gradient Boosting Classifier**

In [ ]:
# Code here: Import Gradient Boosting Classifier


In [ ]:
# Code here: Instantiate a model.

In [ ]:
# Code here: Fit the model

In [ ]:
y_tr_pred = gb_model.predict(X_train_sc)
y_ts_pred = gb_model.predict(X_test_sc)

In [ ]:
get_metrics(y_true = y_train, y_pred = y_tr_pred)

In [ ]:
get_metrics(y_true = y_test, y_pred = y_ts_pred, train=False)

# **Adaptive Boosting**

In [48]:
# Code here: Import AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier

In [57]:
# Code here: Instantiate the model. Use algorithm='SAMME'
ab_model =  AdaBoostClassifier(random_state=R_STATE,algorithm='SAMME')


In [58]:
# Code here: Fit the model
ab_model.fit(X_train_sc,y_train)

/voc/work/.local/lib/python3.10/site-packages/sklearn/ensemble/_weight_boosting.py:519: FutureWarning: The parameter 'algorithm' is deprecated in 1.6 and has no effect. It will be removed in version 1.8.
  warnings.warn(


AdaBoostClassifier(algorithm='SAMME', random_state=12345)

In [59]:
y_tr_pred = ab_model.predict(X_train_sc)
y_ts_pred = ab_model.predict(X_test_sc)

In [60]:
get_metrics(y_true = y_train, y_pred = y_tr_pred)

=========================== Training Set Metrics ==========================
Confusion Matrix
[[3812  327]
 [ 763  732]]

Accuracy Score 80.65%
Precision Score 69.12%
Recall Score 48.96%



In [61]:
get_metrics(y_true = y_test, y_pred = y_ts_pred, train=False)


=========================== Test Set Metrics ==========================
Confusion Matrix
[[943  92]
 [190 184]]

Accuracy Score 79.99%
Precision Score 66.67%
Recall Score 49.2%



# **CatBoost**

In [47]:
!pip install catboost --q

In [ ]:
# Code here: Import CatBoostClassifier

In [ ]:
# Code here: Instantiate the model

In [ ]:
# Code here: Fit your model

In [ ]:
y_tr_pred = cb_model.predict(X_train_sc)
y_ts_pred = cb_model.predict(X_test_sc)

In [ ]:
get_metrics(y_true = y_train, y_pred = y_tr_pred)

In [ ]:
get_metrics(y_true = y_test, y_pred = y_ts_pred, train=False)

# **XGBoost**

In [ ]:
!pip install xgboost --q

In [ ]:
# Code here: Import XGBoostClassifier

In [ ]:
# Code here: Create your model

In [ ]:
# Code here: Fit your model

In [ ]:
y_tr_pred = xg_model.predict(X_train_sc)
y_ts_pred = xg_model.predict(X_test_sc)

In [ ]:
get_metrics(y_true = y_train, y_pred = y_tr_pred)

In [ ]:
get_metrics(y_true = y_test, y_pred = y_ts_pred, train=False)

# **StackingClassifier**

In [ ]:
# Code here: Import Stacking Classifier

In [ ]:
# Code here: List of Models

In [ ]:
# Code here: Instantiate StackingModel. Use list of models as estimators and final model as XGBoost

In [ ]:
st_model.fit(X_train_sc, y_train)

In [ ]:
y_tr_pred = st_model.predict(X_train_sc)
y_ts_pred = st_model.predict(X_test_sc)


In [ ]:
get_metrics(y_true = y_train, y_pred = y_tr_pred)
get_metrics(y_true = y_test, y_pred = y_ts_pred, train=False)