In [1]:
import numpy as np
import pandas as pd

In [2]:
sample_list = [10,20,30,40]
labels = ['a','b','c','d']

In [3]:
sample_array = np.array(sample_list)

In [4]:
sample_array

array([10, 20, 30, 40])

In [5]:
sample_array[2]

30

In [29]:
var1 = pd.Series(data=sample_array,index=labels)

In [30]:
type(var1)

pandas.core.series.Series

In [31]:
var1

a    10
b    20
c    30
d    40
dtype: int32

In [32]:
var1['c']

30

In [13]:
number_of_students = [1,2,3,4]
sports = ['Cricket','Football','Basketball','Tennis']
result = np.array(number_of_students)

In [14]:
result

array([1, 2, 3, 4])

In [16]:
sports1 = pd.Series(data=number_of_students,index=sports)

In [17]:
sports1['Basketball']

3

In [18]:
class2 = {'Cricket': 3, 'Football': 4, 'Tennis': 2}

In [19]:
sports2 = pd.Series(class2)

In [20]:
sports2

Cricket     3
Football    4
Tennis      2
dtype: int64

In [21]:
sports1 + sports2

Basketball    NaN
Cricket       4.0
Football      6.0
Tennis        6.0
dtype: float64

In [22]:
sports1

Cricket       1
Football      2
Basketball    3
Tennis        4
dtype: int64

In [23]:
sports2

Cricket     3
Football    4
Tennis      2
dtype: int64

In [24]:
sports1 + sports2

Basketball    NaN
Cricket       4.0
Football      6.0
Tennis        6.0
dtype: float64

In [42]:
np.random.seed(2)

In [43]:
np.random.rand(10,5)

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987],
       [0.78533515, 0.85397529, 0.49423684, 0.84656149, 0.07964548],
       [0.50524609, 0.0652865 , 0.42812233, 0.09653092, 0.12715997],
       [0.59674531, 0.226012  , 0.10694568, 0.22030621, 0.34982629],
       [0.46778748, 0.20174323, 0.64040673, 0.48306984, 0.50523672],
       [0.38689265, 0.79363745, 0.58000418, 0.1622986 , 0.70075235],
       [0.96455108, 0.50000836, 0.88952006, 0.34161365, 0.56714413],
       [0.42754596, 0.43674726, 0.77655918, 0.53560417, 0.95374223]])

In [44]:
students_marks = pd.DataFrame(data= np.random.rand(10,5), index= 'A B C D E F G H I J'.split(), columns='Score1 Score2 Score3 Score4 Score5'.split())

In [45]:
students_marks

Score1    Score2    Score3    Score4    Score5
A  0.544208  0.082095  0.366342  0.850851  0.406275
B  0.027202  0.247177  0.067144  0.993852  0.970580
C  0.800258  0.601817  0.764960  0.169225  0.293023
D  0.524067  0.356624  0.045679  0.983153  0.441355
E  0.504000  0.323541  0.259745  0.386890  0.832017
F  0.736747  0.379211  0.013017  0.797405  0.269389
G  0.582685  0.025551  0.662202  0.387523  0.497074
H  0.414906  0.350872  0.550978  0.972911  0.112776
I  0.313259  0.041798  0.738400  0.657512  0.214636
J  0.416753  0.643842  0.661481  0.170477  0.881652

In [47]:
students_marks['Score3']

A    0.366342
B    0.067144
C    0.764960
D    0.045679
E    0.259745
F    0.013017
G    0.662202
H    0.550978
I    0.738400
J    0.661481
Name: Score3, dtype: float64

In [48]:
type(students_marks['Score3'])

pandas.core.series.Series

In [49]:
students_marks[['Score3','Score5']]

Score3    Score5
A  0.366342  0.406275
B  0.067144  0.970580
C  0.764960  0.293023
D  0.045679  0.441355
E  0.259745  0.832017
F  0.013017  0.269389
G  0.662202  0.497074
H  0.550978  0.112776
I  0.738400  0.214636
J  0.661481  0.881652

In [50]:
type(students_marks[['Score3','Score5','Score2']])

pandas.core.frame.DataFrame

In [51]:
students_marks[['Score3','Score5','Score2']]

Score3    Score5    Score2
A  0.366342  0.406275  0.082095
B  0.067144  0.970580  0.247177
C  0.764960  0.293023  0.601817
D  0.045679  0.441355  0.356624
E  0.259745  0.832017  0.323541
F  0.013017  0.269389  0.379211
G  0.662202  0.497074  0.025551
H  0.550978  0.112776  0.350872
I  0.738400  0.214636  0.041798
J  0.661481  0.881652  0.643842

In [52]:
students_marks['Score6'] = students_marks['Score2'] + students_marks['Score4']

In [53]:
students_marks

Score1    Score2    Score3    Score4    Score5    Score6
A  0.544208  0.082095  0.366342  0.850851  0.406275  0.932945
B  0.027202  0.247177  0.067144  0.993852  0.970580  1.241029
C  0.800258  0.601817  0.764960  0.169225  0.293023  0.771043
D  0.524067  0.356624  0.045679  0.983153  0.441355  1.339778
E  0.504000  0.323541  0.259745  0.386890  0.832017  0.710431
F  0.736747  0.379211  0.013017  0.797405  0.269389  1.176616
G  0.582685  0.025551  0.662202  0.387523  0.497074  0.413074
H  0.414906  0.350872  0.550978  0.972911  0.112776  1.323783
I  0.313259  0.041798  0.738400  0.657512  0.214636  0.699310
J  0.416753  0.643842  0.661481  0.170477  0.881652  0.814319

In [56]:
students_marks.drop('Score6',axis=1,inplace=True)

In [58]:
students_marks

Score1    Score2    Score3    Score4    Score5
A  0.544208  0.082095  0.366342  0.850851  0.406275
B  0.027202  0.247177  0.067144  0.993852  0.970580
C  0.800258  0.601817  0.764960  0.169225  0.293023
D  0.524067  0.356624  0.045679  0.983153  0.441355
E  0.504000  0.323541  0.259745  0.386890  0.832017
F  0.736747  0.379211  0.013017  0.797405  0.269389
G  0.582685  0.025551  0.662202  0.387523  0.497074
H  0.414906  0.350872  0.550978  0.972911  0.112776
I  0.313259  0.041798  0.738400  0.657512  0.214636
J  0.416753  0.643842  0.661481  0.170477  0.881652

In [61]:
new_student_list = students_marks.drop('I',axis=0)

In [62]:
new_student_list

Score1    Score2    Score3    Score4    Score5
A  0.544208  0.082095  0.366342  0.850851  0.406275
B  0.027202  0.247177  0.067144  0.993852  0.970580
C  0.800258  0.601817  0.764960  0.169225  0.293023
D  0.524067  0.356624  0.045679  0.983153  0.441355
E  0.504000  0.323541  0.259745  0.386890  0.832017
F  0.736747  0.379211  0.013017  0.797405  0.269389
G  0.582685  0.025551  0.662202  0.387523  0.497074
H  0.414906  0.350872  0.550978  0.972911  0.112776
J  0.416753  0.643842  0.661481  0.170477  0.881652

In [63]:
students_marks

Score1    Score2    Score3    Score4    Score5
A  0.544208  0.082095  0.366342  0.850851  0.406275
B  0.027202  0.247177  0.067144  0.993852  0.970580
C  0.800258  0.601817  0.764960  0.169225  0.293023
D  0.524067  0.356624  0.045679  0.983153  0.441355
E  0.504000  0.323541  0.259745  0.386890  0.832017
F  0.736747  0.379211  0.013017  0.797405  0.269389
G  0.582685  0.025551  0.662202  0.387523  0.497074
H  0.414906  0.350872  0.550978  0.972911  0.112776
I  0.313259  0.041798  0.738400  0.657512  0.214636
J  0.416753  0.643842  0.661481  0.170477  0.881652

In [65]:
students_marks.loc['C','Score3']

0.7649598604516815

In [66]:
students_marks.loc['D','Score5']

0.4413549193548467

In [67]:
students_marks.loc['C']

Score1    0.800258
Score2    0.601817
Score3    0.764960
Score4    0.169225
Score5    0.293023
Name: C, dtype: float64